spring:
  application:
    name: UserMgmtAPI
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///krushit40db
    username: root
    password: krushit
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    username: indian.red.cross.in@gmail.com
    password: qjawsbalasifypda
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true

usermgmt:
  messages:
    save-success: User registered with id val
    save-failure: Oops..!! Something went wrong
    update-success: User data is updated
    update-failure: User not found for updation
    delete-success: User deleted with id val
    delete-failure: User is not found for deletion
    user-activation-success: Account avtivated with id val
    user-activation-failure: Oops..!! Account not found for activation
    invalid-credentials: Oops..!! User account not found
    valid-credentials: Welcome
    inavtive-account: account is not active
    status-updation-success: account status is updated as 
    status-updation-fail: Oops..!! Something went wrong

mailBody:
    registerUser:
      location: src/main/java/com/krushit/service/user_registration_mail_body.txt
    recoverPass:
       location: src/main/java/com/krushit/service/revcover_password.txt

server:
    port: 4041